import { mkdirSync, writeFileSync } from 'node:fs';
import { characters } from '../src/data/characters';

// Art direction only. This script writes prompts, never draws or assembles characters.
const portraits: Record<string, { pose: string; palette: string; recognition: string }> = {
  'su-shi': { pose: 'A relaxed walking scholar turns his head into the breeze, one hand lightly holding a bamboo walking stick, the other gathering his loose robe. Broad rain hat, a small wine gourd at his waist, a gently swinging robe hem. His posture feels open and unhurried.', palette: 'near-black ink, muted blue-green sleeve shading, weathered straw brown', recognition: '竹杖、宽檐笠、随风行走、腰间葫芦' },
  'wang-yangming': { pose: 'A composed Ming scholar stands in a quiet three-quarter pose with one hand holding a partly rolled manuscript and the other tucked into a wide sleeve at his chest. Plain scholar cap and restrained layered robes. A slight forward step conveys thought becoming action; no armor or royal insignia.', palette: 'near-black ink, subtle pine-green and blue-grey folds', recognition: '方巾、文卷、收袖凝思、迈步而行' },
  'cao-cao': { pose: 'A decisive late-Han commander looks outward in side profile, broad cloak swept to one side by wind, one hand resting firmly on the hilt of a sheathed straight sword. A tall Han-style formal cap and compact mustache/beard silhouette. Proud but contained posture, not a fantasy warrior.', palette: 'near-black ink, deep oxblood cloak shading, restrained aged-bronze fastenings', recognition: '高冠、披风、按剑、侧望远方' },
  'zhuge-liang': { pose: 'A serene strategist in a tall folded scholar headcloth and long crane-style cloak holds an unmistakable white feather fan across his torso. His head is slightly inclined; his free hand is hidden naturally in his other broad sleeve. The fan and curved drape form a distinctive balanced silhouette.', palette: 'near-black ink, muted midnight blue folds, ivory feather fan', recognition: '纶巾、羽扇、鹤氅、收袖静立' },
  'li-bai': { pose: 'An exuberant Tang poet leans slightly back, chin lifted toward a small wine cup raised high in one hand. The raised arm carries an enormous draped sleeve in a sweeping curve. His other hand rests beside a sheathed straight Chinese sword, with a double-gourd flask at the waist and a loose hair ribbon behind his topknot. Preserve the effortless upward gesture, not a stiff standing mannequin.', palette: 'near-black ink robe, soft charcoal-brown sleeve highlights, muted brown gourd and cup', recognition: '仰首举杯、长剑、葫芦、飘带' },
  'tao-yuanming': { pose: 'A rustic poet in a broad straw hat walks quietly while carrying a small woven basket with a few chrysanthemum stems. His other hand gently holds one chrysanthemum at chest height. Loose simple robes and a low, relaxed shoulder line, no ornate scholar or court costume.', palette: 'near-black ink, moss-grey cloth shading, straw brown basket and a small muted yellow flower', recognition: '斗笠、菊花、竹篮、布袍' },
  'liu-bang': { pose: 'An approachable early-Han leader turns three-quarter toward the viewer with one wide sleeve opening in a welcoming gesture, palm relaxed. A simple red-accented Han crown, long layered robe and one circular jade belt pendant. The other arm rests by the waist; his open posture is the main identity cue.', palette: 'near-black ink, warm dark red robe folds, a small subdued jade pendant', recognition: '汉冠、开袖迎人、佩环' },
  'qin-shi-huang': { pose: 'A solemn Qin ruler stands with a commanding near-frontal silhouette, a rectangular ceremonial crown with sparse hanging bead strands, broad black robes, narrow red trim. Both hands rest naturally on the pommel of a vertically sheathed long sword in front of him. Keep the head small and the ceremonial silhouette majestic and elongated, no throne.', palette: 'dense black, very dark red trim, small antique-gold details', recognition: '冕旒、玄衣、正立长剑、仪式感' },
  'zhang-juzheng': { pose: 'A focused Ming statesman wears a recognizable black winged official hat, formal long robe, jade-panel belt and holds a slender ivory ceremonial tablet in one hand, the other hand covered by his sleeve. Slightly turned body, disciplined posture, restrained chest insignia rather than dense ornament.', palette: 'near-black ink, muted aubergine cloth, ivory tablet, very sparse jade accents', recognition: '乌纱帽、玉带、笏板、端正立姿' },
  'wang-anshi': { pose: 'A spare Song scholar-official bends slightly toward an open paper manuscript held across both hands, as if carefully reviewing an idea. Plain dark scholar headwear, narrow shoulders and wide unadorned sleeves. One rolled document is tucked into his belt. Silhouette is attentive and quietly resolute.', palette: 'near-black ink, muted olive-green shadows, parchment manuscript', recognition: '朴素冠巾、展开文书、俯身审读' },
  'xin-qiji': { pose: 'An athletic but elongated Song poet-warrior stands side-on drawing a traditional Chinese longbow. One arm extends the bow and the other pulls the arrow toward his cheek, with anatomically coherent hands and a taut bowstring. Bound topknot, flowing broad sleeves, a restrained dark-russet outer robe. The bow must read clearly and fit entirely inside the frame.', palette: 'near-black ink, dark russet sleeve shading, brown wooden bow', recognition: '挽弓、箭矢、束发、侧身劲姿' },
  'sima-qian': { pose: 'A persistent Han historian sits low beside a minimal writing support and leans into a bamboo-slip manuscript. One hand writes with a brush, the other steadies the slips. Modest low cap, long robe folded beneath him. The seated curved silhouette and bamboo record are central; only this small writing support, no furnished room.', palette: 'near-black ink, subdued slate-blue folds, bamboo tan', recognition: '低冠、伏案执笔、竹简、坐姿' },
  'zheng-he': { pose: 'A confident Ming maritime envoy stands three-quarter with an unfolded navigation chart held diagonally across his body. A Ming formal cap and long cloak caught slightly by a sea breeze, its outer curve suggesting a sail. The gaze is lifted toward an imagined horizon. No ship, water or background scene; the chart has only abstract route marks.', palette: 'near-black ink, muted deep teal cloak, parchment and sparse bronze details', recognition: '明式冠帽、海图、迎风披衣' },
  'han-xin': { pose: 'A lean Han commander inclines forward in an intent strategic gesture, one hand indicating a route on a small unfurled campaign map held by the other. A restrained period helmet, cloak, sparse lamellar armor at the waist and a sheathed straight sword angled beside him. Avoid generic armored bulk; the leaning pose and map distinguish him.', palette: 'near-black ink, muted steel-blue folds, parchment map, aged-bronze armor hints', recognition: '战盔、指图、斜剑、前倾谋划' },
  'wu-zetian': { pose: 'A commanding Tang woman ruler stands poised and nearly frontal, wearing a simplified high gold floral-and-phoenix ceremonial crown, broad layered formal robes, one hand holding a short closed court scroll and the other resting within an expansive curved sleeve. Her chin is subtly raised and shoulders open. No European scepter, no fantasy crown or throne.', palette: 'near-black ink, dark wine-purple sleeves, restrained antique gold crown', recognition: '唐式高冠、凤形冠饰、敕卷、开阔肩袖' },
  'li-qingzhao': { pose: 'An independent Song woman poet stands slightly turned, holding a delicate round silk fan loosely at her side while studying a small folded poetry sheet in her other hand. Elegant restrained hair coils and one simple hairpin, soft long sleeves with an expressive descending curve. Quietly attentive rather than coy or decorative.', palette: 'near-black ink, muted indigo-violet sleeve shading, pale warm ivory fan', recognition: '素雅发髻、团扇、诗页、凝视细读' },
  'shangguan-waner': { pose: 'A cultivated Tang woman writer holds a slender calligraphy brush poised above a small scroll in the other hand. A high swept-up hairstyle with one understated ornamental pin, long sleeves whose asymmetrical curves frame the poised brush. Head lifted slightly as if choosing a phrase, no decorative butterflies or floating symbols.', palette: 'near-black ink, restrained plum-purple sleeves, dusty rose sash, parchment scroll', recognition: '唐式高髻、悬笔、书卷、不对称长袖' },
  'ban-zhao': { pose: 'A learned Han woman stands in a gentle teaching gesture with an opened bundle of bamboo slips supported in one hand and the other hand indicating a line. Plain hair bun and simple pin, modest layered Han robes, a measured upright silhouette. Use bamboo slips, not a modern bound book.', palette: 'near-black ink, muted dark jade cloth, bamboo tan', recognition: '汉式素髻、竹简、指读讲授' },
  'cai-wenji': { pose: 'A reflective Han woman musician sits low in a flowing cloak and head covering, holding a period-inspired lute diagonally against her torso. One hand rests on its neck, the other lightly touches the strings. A long scarf forms a quiet curve across the shoulder. Her compact seated silhouette should feel resilient and lyrical.', palette: 'near-black ink, muted smoky blue cloak, warm aged-wood lute', recognition: '披帛兜帽、斜抱琵琶、低坐、拨弦' },
  'fu-hao': { pose: 'A powerful Shang woman commander stands in a grounded three-quarter pose holding a broad bronze yue battle axe vertically beside her. Restrained Shang-inspired headdress, sparse bronze armor over a long dark garment, broad belt. One arm is firm on the axe shaft, the other relaxed near the waist. Ancient Chinese bronze shape, no Viking horns or European armor.', palette: 'near-black ink, dark warm-brown armor shading, restrained aged bronze', recognition: '青铜钺、商式冠饰、甲衣、稳健立姿' },
  'lu-zhi': { pose: 'An authoritative early-Han empress dowager stands in a contained frontal pose, a small ceremonial seal with a red cord held securely between her hands. A layered Han court headdress and overlapping broad black-and-dark-red robes create a closed, protective silhouette. Firm posture, no sinister caricature.', palette: 'near-black ink, dark red inner robe, antique-gold seal', recognition: '汉式层冠、捧印、黑红交叠衣袍' },
  zhangsun: { pose: 'A composed Tang empress turns slightly in a mediating, attentive pose. One hand holds a round fan low at the waist; the other softly gathers a long draped silk shawl. Restrained floral court crown, the shawl makes one broad graceful arc around her arms. Her posture is dignified and calm, not passive.', palette: 'near-black ink, muted sage-jade shadows, warm ivory silk and sparse gold ornament', recognition: '花形冠、圆扇、舒展披帛、侧身倾听' },
  'zhuo-wenjun': { pose: 'A free-spirited Han woman sits side-on at a minimal low guqin, both hands naturally placed over its strings. A long loose silk ribbon falls from her hair and a wide sleeve curves toward the instrument. The guqin is a long flat Chinese zither, not a keyboard or lute. Only a minimal low support under the instrument, no interior scene.', palette: 'near-black ink, muted dusty-rose and plum robe shading, aged dark wood', recognition: '侧坐抚琴、长绸带、古琴' },
  'feng-taihou': { pose: 'A purposeful Northern Wei woman ruler stands slightly angled while holding a narrow bundle of policy slips in one hand; the other hand settles the edge of a structured draped shoulder mantle. A stylized Northern Dynasties tall formal headdress, compact shoulders and long clear robe lines. Blend formal authority and forward-looking movement without copying Tang court costume.', palette: 'near-black ink, muted blue-grey mantle, restrained ochre-gold edging', recognition: '北朝高冠、披肩、策简、微转立姿' },
};

const style = `Use case: stylized-concept.
Asset type: one finished raster historical-character illustration for a Chinese personality app.
Reference image 1: style reference of a single poet. Reference image 2: the isolated right-column character illustrations from the user's poster. Use only their character drawing style; do not reproduce typography, logos, screenshot layout or the poster's wheel.
Style: sophisticated contemporary Chinese character illustration. Elegant elongated proportions, small pale-pink nearly featureless face in a carefully designed profile or three-quarter angle, black hair. Large expressive continuous silhouettes, flowing robe hems and generous sleeve curves, a few crisp angular folds. Near-black fabrics with subtle desaturated colored gradients and fine restrained grain. Natural, intentional posture and coherent anatomy. The figure must feel painted as one complete composition, not assembled from reusable geometric body parts. Match the references' sophistication, shape rhythm and controlled detail.
Composition: exactly ONE character, isolated, complete clothing and all props inside the canvas. Leave at least 7% clear margin around the outermost hat, sleeve, weapon and robe hem. Vertical composition, no text area baked into the image. No extra people, contact sheet or collage.
Background: real transparent alpha; keep the fabrics opaque. No rectangular paper background, ground shadow, scenery, halo, vignette or checkerboard painted into the image.
Avoid: modern anime, chibi, photorealism, 3D toy, polygon mannequin, flat clipart, explicit polygon facets, identical front-facing poses, tiny overloaded ornament, modern accessories, extra limbs, extra hands, words, letters, signatures, watermarks and logos.
This is a culturally recognizable artistic interpretation, not an archaeological portrait reconstruction. Props should suit the person's cultural associations and period. No text labels are needed to distinguish the person.`;

const out = 'output/imagegen';
mkdirSync(`${out}/prompts`, { recursive: true });
const manifest = characters.map(c => {
  const art = portraits[c.id];
  if (!art) throw new Error(`Missing portrait brief: ${c.id}`);
  const prompt = `${style}\n\nSubject: ${c.name}, ${c.era}, ${c.identity}.\nIndividual character and gesture: ${art.pose}\nPalette: ${art.palette}.\nThe pose, headdress and primary prop are essential recognition cues. Produce a fresh high-quality complete illustration, not an SVG or any code drawing.\n`;
  writeFileSync(`${out}/prompts/${c.id}.txt`, prompt);
  return { id:c.id, name:c.name, recognition:art.recognition, pose:art.pose, palette:art.palette, promptFile:`${out}/prompts/${c.id}.txt`, model:'gpt-image-2.5-sunburst', quality:'high', size:'1024x1536', status:'prepared', sourceFile:`${out}/originals/${c.id}.png` };
});
writeFileSync(`${out}/character-manifest.json`, JSON.stringify(manifest,null,2));
writeFileSync(`${out}/ART-DIRECTION.md`, `# 人物插画生成方案\n\n状态：24 份提示词已准备。仅实际生成、检查通过的文件才会替换网页资产。\n\n指定模型：GPT-Image-2.5 Sunburst。每位人物单独生成，使用相同的两张风格参考。透明背景，高质量，1024 × 1536；后续只做尺寸与透明边距整理，不用代码拼接人物。\n\n## 统一风格\n\n修长比例、极简面部、连续的大衣袍轮廓、流动曲线、墨黑与低饱和渐变、克制颗粒感。人物的动作和道具优先于装饰细节。\n\n## 24 位人物\n\n| 人物 | 识别线索 |\n| --- | --- |\n${manifest.map(c=>`| ${c.name} | ${c.recognition} |`).join('\n')}\n\n完整提示词位于 prompts/，逐人元数据位于 character-manifest.json。\n`);
console.log(`Prepared ${manifest.length} distinct character prompts; no images generated by this script.`);
